version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-network

  nestjs-app:
    build: ./nest-app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/productDevTest
      JWT_SECRET: ${JWT_SECRET}
      EXPIRES_JWT: ${EXPIRES_JWT}
    depends_on:
      - postgres
    networks:
      - backend-network

  nextjs-app:
    build: ./front-next-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - nestjs-app
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  pgdata: